### ISSUE TITLE
Registration Table: Welcome Sign & Instruction poster

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2018#100]
Branching off from https://github.com/MozillaFoundation/mozfest-design-2018/issues/44

### Description:
When attendees enter the venue, there is registration signage to welcome them and provide instructions for Icebreaker Game/ Language/Pronouns Sticker.

### This collection of signs include

- [ ] Welcome sign (with l10n incorporated) https://github.com/mozilla/mozillafestival.org/issues/720
- [ ] Instructions about Icebreaker Game/ Language/Pronouns Sticker Sign
   - [Copy for Icebreaker instructions](https://github.com/MozillaFoundation/mozfest-design-2018/issues/58#issuecomment-423671382)

Can be in A3/A4 size paper to put up on the registration table.

**Comment by sabrinang** [comment]
I made a A3 poster for the name card customization instructions: https://redpen.io/rt30b67c64b280391c

@acabunoc From your comment https://github.com/MozillaFoundation/mozfest-design-2018/issues/58#issuecomment-423671382 Should we just go with 4 squares? and what level is the Open Leadership Zone on? The previous poster included `Symmetrical matches count too!` so I added that line in as well (I think it works).

@gideonthomas We don't have any previous copy context for the language and pronoun stickers, any suggestions what should we write?

**Comment by gideonthomas** [comment]
@Saallen how does this sound for the language/pronouns section (i would remove the title from this part):

Let others know what languages you speak and your gender pronouns by writing them on these stickers and attaching them to your name tag.

**Comment by sabrinang** [comment]
I updated the redpen: https://redpen.io/rt30b67c64b280391c

note: instead of `gender pronouns` can we use`preferred pronouns` instead?

**Comment by gideonthomas** [comment]
My mistake, I would say "preferred gender pronouns" actually, using this - https://uxdesign.cc/designing-forms-for-gender-diversity-and-inclusion-d8194cf1f51 as a reference (Mozilla uses it for D&I research)

Side-note: It's kinda weird that the stickers are localized but the poster isn't. Something we should consider for next year.

**Comment by abbycabs** [comment]
@sabrinang we're on level 7 by the stairs!
I'm running the math and slightly concerned that 4 squares will have too many permutations and not enough matches... Haven't considered symmetrical matches yet though.

Let's go with 4 for now and I'll update later today/tomorrow once I figure out the permutations

**Comment by Saallen** [comment]
Happy to use language that Mozilla D&I approve.

**Comment by abbycabs** [comment]
After some thought, can we change it to fill in *3 squares*?

That’s give us something closer to a 1/50 chance to find a match

**Comment by sabrinang** [comment]
@acabunoc I revised the design by changing it to 3 squares bold and underlined. I also changed it to "grid sticker" instead of just "sticker" to make it more clear (since we have other stickers too). I added level 7 and made the symmetrical examples on the bottom more distinct from the grid sticker itself.

@gideonthomas I changed the language to “preferred gender pronouns” as well.

For the welcome sign, welcome is in other languages in the background texture of the sign. 

<img width="661" alt="image" src="https://user-images.githubusercontent.com/2492510/47242642-37427680-d3a4-11e8-83ca-455a41c1cd76.png">
Redpen has been down so can you review PDF files on gdrive;

- Name card sticker instructions sign: https://drive.google.com/drive/folders/1dFmz3zUYpX1h8y2gyGCoTkoTbJkiUX1R

- Welcome sign: https://drive.google.com/file/d/1eWFoPqtBFJqf4I3wzYkd6_NSFrD_SNQy/view
 
@marcwalsh They are currently exported with small bleed (3mm) let me know which template I should use for these A3s to make them stand on the tables

**Comment by abbycabs** [comment]
You're amazing, @sabrinang! Thanks, this looks great to me :)

**Comment by Saallen** [comment]
Looks great- thanks for this @sabrinang and @acabunoc

**Comment by gideonthomas** [comment]
@marcwalsh I left this to you to decide if you want to print on-site or with Pixart. Feel free to change the label accordingly.

**Comment by abbycabs** [comment]
Hey @sabrinang -- is it cool if I remix a version of this with just the sticker match portion to hang around the venue? So when people find their match during the day the instructions will be posted & they can look up where to go? (instead of having to go back to registration to look up where to go)

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The welcome sign and sticker match instructions were on rigid media and we ended up using the dowels to prop them up on the table but they weren’t very sturdy and we used white tac to secure it. I think the welcome sign was pinned on the back board later which kept the table area more clear.

![img_6137](https://user-images.githubusercontent.com/2492510/48652656-7240c580-e9b5-11e8-8a57-d9d1985d5901.JPG)
![20180928-mozfest-sunday-53](https://user-images.githubusercontent.com/2492510/48652780-27737d80-e9b6-11e8-952c-ad5a9a4d707f.jpg)
