### ISSUE TITLE
Social: Graphic for MozFest House

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#16]
Create a graphic that will accompany social media posts about MozFest House.

**Copy:** TBD
**Date to be Posted:**  TBD
**Platforms:** Twitter

**Comment by Saallen** [comment]
Looping in @KGorr to provide content and assitance with this issue

**Comment by KGorr** [comment]
We're going to keep these general so they are promoting the entire week, not individual events. 
Content: MozFest House; dates (feel free to add in anything else regarding general direction of MozFest House design.)

It would be great to have these around the same time the MozFest House website page is updated so that we can share immediately afterwards.

**Comment by sabrinang** [comment]
@KGorr I made a few generic MozFest House social share graphics and some with date information. 
Please see redpen: https://redpen.io/p/ye036ba5b0f3edecbf
<img width="988" alt="image" src="https://user-images.githubusercontent.com/2492510/45715336-e80cea00-bb48-11e8-8147-4843659c2ed1.png">


JPGs on google drive: https://drive.google.com/open?id=1rG7uCFeB7A14QDvr7ucM9p3OnhIJiiJE

@zee-moz Do I tag you to review the social assets?

/cc @gideonthomas

**Comment by KGorr** [comment]
@sabrinang - These are wonderful! I also shared with Lucie and she thinks they are great too! We appreciate all of your hard work. Feel free to close this when you are ready.

**Comment by sabrinang** [comment]
Thanks @KGorr - closing issue
