### ISSUE TITLE
MoFo Program/MozFest Vinyl Banner

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2018#88]
We want to create a vinyl banner to showcase MoFo programs at the festival.

Design Deadline - (@xmatthewx can you edit this comment with this info...latest I believe is Sep 30).

@marcwalsh would you be able to let us know if there is budget for this, and if so, what dimensions can we print?

**Comment by xmatthewx** [comment]
**Cost**: The cost for this and any MoFo program stuff shouldn't come from MozFest unless it's nominal. This would be the Awards/Fellowship team.

**Comment by xmatthewx** [comment]
@taisdesouzalessa

**timeline**: Vinyl might have very quick turnaround requirement. Or it might be too late. Quick is feasible since design should be simple. But...

**Orientation**: We'll need to confirm with Melissa that vertical is a good idea, and whether they plan to purchase a stand. (Also, they might look to us for guidance on that, so quick research would be necessary.) Otherwise, horizontal might be better for mounting on a table. 

If vinyl isn't possible now, we can still order one for the future, and go with paper for now. 

cc @kristinashu

**Comment by taisdesouzalessa** [comment]
@xmatthewx and @kristinashu  - I quickly chatted with Melissa via Slack to confirm what I heard from the meeting we had yesterday and here are their needs for this item:

1. Vinyl roll-up banner with a stand would be good for them so they can carry it to other events as well (and also share it with other teams as needed in the future). Based on the banner layout (it could be the same), they would like to have a large paper banner to hang off the balcony < I think this can be printed at Ravensbourne. Correct me if I am wrong @marcwalsh.
2. If 1 is not possible due to printing deadlines, they are okay with the paper version. Once they have the design they could print it in vinyl in a later date.

**Comment by gideonthomas** [comment]
@taisdesouzalessa like one of these? https://www.pixartprinting.co.uk/displays/roller-banners/

**Comment by taisdesouzalessa** [comment]
@gideonthomas I think so. It does stand up by itself right? Like, it comes with the structure and you can transport and assemble it? I can double check with Melissa tomorrow but in my understanding this is what she meant.

**Comment by marcwalsh** [comment]
@taisdesouzalessa @gideonthomas @xmatthewx 

If it's just a standard roller banner, that stands by itself and rolls up and down as needed. Turnaround times can be very quick. The [cube version](https://www.pixartprinting.co.uk/displays/roller-banners/roll-up-cube/) is probably the easiest to transport. 

If you only need this in time for Friday of the festival weekend, ideally I'd like the content by the 18th October. 

[Template attached here.](https://github.com/MozillaFoundation/mozfest-design-2018/files/2428271/pixartprinting-template-large-format-roll-up-cube.pdf)

**Comment by xmatthewx** [comment]
Thanks @marcwalsh! So these can have a full bleed?

**Comment by taisdesouzalessa** [comment]
Thanks for the reply and the template @marcwalsh - another question I have is resolution - do you know if we need it at 300 pixels/inch if designing in final size or is 100 pixels/inch enough?

**Comment by sabrinang** [comment]
@taisdesouzalessa I'd export 300 dpi if possible

**Comment by gideonthomas** [comment]
Closing as this is being tracked in the Design repo and print being handled by designers.
